### ISSUE TITLE
No app focus, hover not working, stuck in oculus home

### ISSUE THREAD

**Issue by Woogoo336** [KrisIsBackAU/Oculus-VR-Dash-Manager#2]
This app is exactly what I'm looking for but I ran into a few issues.

In SteamVR mode, the app will not focus and forces a win+tab view whenever selecting it. The app also doesn't detect the cursor for hover activation when it is on top with the setting enabled. I also found that with the "quick start" option enabled and clicking oculus killer, I am simply stuck in the oculus home environment with no controller use.

**Comment by KrisIsBackAU** [comment]
Steam VR prevents access to 'Admin' programs  which is a pain in the ass and has no work around as that is how Steam designed Steam VR to operate, that's why the program runs as top most and why hover to activate exists. 

The latest version is a rebuild and should behave better havent heard anything from the early testers that focusing isnt working.

But yes trying to alt tab or win tab to the form WILL have some odd effects, the UI has a detector for it and should resolve its self in a few seconds but I recommend having it visible on the side somewhere.

Wish it was fixable but its not, the Win + Tab is caused by Steam VR.
